apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
  namespace: projeto
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: insanemor/netcat:{{ .Values.container.tag }}
        ports:
        {{- range .Values.ports }}
        - containerPort: {{ .port }}
        {{- end }}
        volumeMounts:
        - name: ports.ini
          mountPath: /app/script/ports.ini
      volumes:
      - name: ports.ini
        configMap:
          defaultMode: 0600
          name: {{ .Values.app.name }} 
