apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  labels:
    name: {{ .Values.app.name }}
    app: {{ .Values.app.name }}
    version: 0.0.1
spec:
  type: NodePort
  # Optional - make the service headless by uncommenting the next line
  # clusterIp: None
  selector: 
    app: {{ .Values.app.name }}
  
  ports:
  {{- range .Values.ports }}
  - name: port-{{ .port }}
    protocol: TCP
    port: {{ .port }}
  {{- end }}