apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: 'https://kubernetes.default.svc'
  project: infra-apps
  revisionHistoryLimit: 1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  source:
    repoURL: https://github.com/kubernetes-sigs/metrics-server
    path: charts/metrics-server
    targetRevision: metrics-server-helm-chart-3.6.0
